#ifndef _GSENSOR_CALIBRATION_H
#define _GSENSOR_CALIBRATION_H

#include "SensorsHeader.h"

#define DEFAULT_SENSITIVITY 256
#define CONTROL_REGISTERS  0x08

#define CONFIG_GSEN_CALIBRATION_GRAVITY_ON_Z_NEGATIVE 1
#define CONFIG_GSEN_CALIBRATION_GRAVITY_ON_Z_POSITIVE 2
#define CONFIG_GSEN_CALIBRATION_GRAVITY_ON_Y_NEGATIVE 3
#define CONFIG_GSEN_CALIBRATION_GRAVITY_ON_Y_POSITIVE 4
#define CONFIG_GSEN_CALIBRATION_GRAVITY_ON_X_NEGATIVE 5
#define CONFIG_GSEN_CALIBRATION_GRAVITY_ON_X_POSITIVE 6

static raw_data offset;

void gsensor_calibrate(int side);

#endif